# Generated by Django 3.2.7 on 2021-10-04 01:46

from django.db import migrations, models
import rarity.services


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-score']},
        ),
        migrations.AlterField(
            model_name='collection',
            name='distribution',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='included_keys',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='policy_id',
            field=models.CharField(max_length=56, primary_key=True, serialize=False, validators=[rarity.services.validate_policy_id]),
        ),
    ]
