# Generated by Django 3.2.7 on 2021-09-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='num',
        ),
    ]
