# Generated by Django 3.2.7 on 2021-09-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='twitter',
            field=models.URLField(blank=True, max_length=23),
        ),
    ]
