# Generated by Django 3.2.7 on 2021-10-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0002_auto_20211004_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
