# Generated by Django 3.2.7 on 2021-09-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0002_project_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='property_keys',
            field=models.JSONField(null=True),
        ),
    ]
