# Generated by Django 3.2.7 on 2021-09-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0002_auto_20210928_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='onchain_metadata',
            field=models.JSONField(null=True),
        ),
    ]
