# Generated by Django 3.2.7 on 2021-09-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0003_collection_property_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['project']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='asset',
            name='str_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
