# Generated by Django 3.2.7 on 2021-10-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0003_alter_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='rank',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
