# Generated by Django 3.2.7 on 2021-10-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0004_asset_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
