# Generated by Django 3.2.7 on 2021-09-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0004_auto_20210925_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['num']},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='str_name',
        ),
        migrations.AddField(
            model_name='asset',
            name='num',
            field=models.PositiveBigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
