# Generated by Django 3.2.7 on 2021-09-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0005_auto_20210925_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='num',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
