# Generated by Django 3.2.7 on 2021-09-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0006_alter_asset_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='num',
            field=models.PositiveBigIntegerField(),
        ),
    ]
