# Generated by Django 3.2.7 on 2021-10-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0006_alter_asset_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['rank']},
        ),
    ]
