# Generated by Django 3.2.7 on 2021-10-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0007_alter_asset_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-score']},
        ),
    ]
