# Generated by Django 3.2.7 on 2021-10-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0009_alter_asset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='query_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
