# Generated by Django 3.2.7 on 2021-10-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0010_project_query_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='serial',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
