# Generated by Django 3.2.7 on 2021-10-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0011_asset_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='id',
            new_name='alpha_name',
        ),
    ]
