# Generated by Django 3.2.7 on 2021-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0012_rename_id_asset_alpha_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='market',
            field=models.JSONField(null=True),
        ),
    ]
