# Generated by Django 3.2.7 on 2021-11-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0015_remove_asset_decoded_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='fingerprint',
            field=models.CharField(max_length=44),
        ),
    ]
