# Generated by Django 3.2.7 on 2021-11-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0016_alter_asset_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
