# Generated by Django 3.2.7 on 2021-11-14 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rarity', '0020_collection_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-release_date']},
        ),
    ]
